config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    resources :products, only: [:index, :show]
    resources :infos, only:[:index, :show]
    resources :careers, only: [:index, :show]

    resource :search, only: :show
    resources :messages, only: [:new, :create]

    get 'product' => 'static_pages#product'
    get 'product_detail' => 'static_pages#product_detail'
    get 'laboratory' => 'static_pages#laboratory'
    get 'support' => 'static_pages#support'
    get 'privacy' => 'static_pages#privacy'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'static_search' => 'static_pages#search'

    get 'about' => 'static_pages#about'
    get 'about_introduction' => 'static_pages#about_introduction'
    get 'about_honors' => 'static_pages#about_honors'

    # get 'careers' => 'static_pages#careers'
    get 'careers_detail' => 'static_pages#careers_detail'

    namespace :admin do
      root 'home#show', as: 'root'
      resources :home, only: [:show, :edit, :update]
      resources :products
      resources :infos do
        collection do
          post :upload
        end
      end
      resources :about, only: [:show, :edit, :update]
      resources :laboratories, only: [:show, :edit, :update]
      resources :careers
      resources :users, except: [:show, :edit, :update]
      resources :messages, except: [:new, :create]

      get '/login', to: 'sessions#new'
      post '/login', to:'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end

end

app/models/about.rb
class About < ApplicationRecord
	translates :summary, :introduce, :course, :ceo
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career.rb
class Career < ApplicationRecord
	default_scope -> { order(created_at: :desc) }

	validates :position, presence: true

  translates :position, :place, :content

end

app/models/home.rb
class Home < ApplicationRecord
	translates :copywrite1, :copywrite2, :advantage
end

app/models/info.rb
class Info < ApplicationRecord
	default_scope -> { order(created_at: :desc) }

	has_many :pictures, dependent: :destroy

	validates :title, presence: true

	translates :title, :content

end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
	translates :laboratory_title_content, :rd_title, :rd_content, :hsf_title, :hsf_content, :hsf_list, 
	           :multimedia_title, :multimedia_content, :multimedia_list, :power_title, :power_content, :power_list,
	           :mechanical_title, :mechanical_content, :mechanical_list, :chemistry_title, :chemistry_content, :chemistry_list,
	           :audio_title, :audio_content, :audio_list, :anechoic_title, :anechoic_content, :anechoic_list,
	           :subjectivity_title, :subjectivity_content, :subjectivity_list, :salt_title, :salt_content, :salt_list
end

app/models/message.rb
class Message < ApplicationRecord
	validates :name, presence: true
	validates :mobile, presence: true
	validates :email, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :info, required: false

  validates :image, presence: true
  mount_uploader :image, PictureUploader
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :photo1, presence: true
	validates :photo2, presence: true

	translates :feature

	mount_uploader :photo1, PhotoUploader
	mount_uploader :photo2, PhotoUploader
	mount_uploader :configuration1, PhotoUploader
	mount_uploader :configuration2, PhotoUploader
	mount_uploader :curve1, PhotoUploader
	mount_uploader :curve2, PhotoUploader



	# def self.search(search)
	#   if search
	#     where("name = ?", "#{search}")
	#   else
	#     all
	#   end
	# end


end

app/models/search.rb
class Search < ApplicationRecord
  def products
    @products ||= find_products
  end

  private

  def find_products
    return Product.none if attributes.except('id', 'created_at', 'updated_at').all? { |_k, v| v.blank? }
    products = Product.order(:name)
    products = products.where("name like ?", "%#{name}%") if name.present?

    products = products.where(category: category) if category.present?

    if product_type.present? && product_type == 4
      products = products.all
    else
      products = products.where(product_type: product_type) 
    end
    
    products = products.where("fo >= ?", min_fo) if min_fo.present?
    products = products.where("fo <= ?", max_fo) if max_fo.present?

    products = products.where("rated_power >= ?", min_rated_power) if min_rated_power.present?
    products = products.where("rated_power <= ?", max_rated_power) if max_rated_power.present?

    products = products.where("sensitivity >= ?", min_sensitivity) if min_sensitivity.present?
    products = products.where("sensitivity <= ?", max_sensitivity) if max_sensitivity.present?

    products = products.where("size_length >= ?", min_size_length) if min_size_length.present?
    products = products.where("size_length <= ?", max_size_length) if max_size_length.present?

    products = products.where("size_width >= ?", min_size_width) if min_size_width.present?
    products = products.where("size_width <= ?", max_size_width) if max_size_width.present?

    products = products.where("size_height >= ?", min_size_height) if min_size_height.present?
    products = products.where("size_height <= ?", max_size_height) if max_size_height.present?

    products
  end
end

app/models/user.rb
class User < ApplicationRecord

	before_save { self.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
						format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def index
  	@careers = Career.all
  end

  def show
  	@career = Career.find(params[:id])
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
  	@infos = Info.paginate(page: params[:page], :per_page => 8)
  end

  def show
  	@info = Info.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @home ||= Home.first
  end

  def support
    @message = Message.new
  end

  def product
  end

  def product_detail
  end

  def news
  end

  def news_content
  end

  def about
    @about = About.first
  end

  def about_introduction
    @about = About.first
  end

  def about_honors
  end

  def careers
  end

  def careers_detail
  end

  def search
  end

  def laboratory
    @laboratory ||= Laboratory.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = t("title")
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

	def full_category(category)
  	if category == 1
  		'电视扬声器'
  	else
  		'其他扬声器'
  	end
  end

  def full_product_type(product_type)
    if product_type == 1
      '单体扬声器'
    elsif product_type == 2
      '箱体扬声器'
    else product_type == 3
      '汽车扬声器'
    end
  end

  def info_category(category)
  	if category == 1
  		I18n.t("infos.news")
  	elsif category == 2
  		I18n.t("infos.announcement")
  	else
  		I18n.t("infos.information")
  	end
  end

  def prodcut_find(name)
    Product.find_by(name: name)
  end

  def is_active_controller(controller_name)
    params[:controller] == controller_name ? "active" : nil
  end

  def is_active_action(action_name)
    params[:action] == action_name ? "active" : nil
  end


end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="about-jumbotron">
  <div class="container">
    <div class="content">
      <h2><%= t(".title") %></h2>
    </div>
  </div>
</div>

<div class="container">
	<div class="row contact">
	  <div class="row about-contact">
	  	<div class="col-md-4">
	  		<blockquote class="blockquote-reverse introduction-blockquote">
				  <h4 class="about-head"><%= t(".profile") %></h4>
				</blockquote>
	  	</div>
		  <div class="col-md-8">
		  	<p>
		  		<%= @about.summary %>
		  	</p>
		  	<%= link_to t(".more"), about_introduction_path, class: "btn btn-primary", role: "button" %>
		  </div>
		</div>

		<div class="row about-contact">
	  	<div class="col-md-4">
	  		<blockquote class="blockquote-reverse operation-blockquote">
				  <h4 class="about-head"><%= t(".history") %></h4>
				</blockquote>
	  	</div>
		  <div class="col-md-8">
		  	<p>
		  		<%= @about.course %>
		  	</p>
		  	<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal"><%= t(".details") %></button>
		  </div>
		  <!-- Modal -->
				<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				  <div class="modal-dialog modal-lg" role="document">
				    <div class="modal-content">
				    	<%= render 'static_pages/milestones' %>
				    </div>
				  </div>
				</div>
		</div>

		<div class="row about-contact">
	  	<div class="col-md-4">
	  		<blockquote class="blockquote-reverse ceo-blockquote">
				  <h4 class="about-head"><%= t(".president") %></h4>
				</blockquote>
	  	</div>
		  <div class="col-md-8">
		  	<%= simple_format(@about.ceo) %>
		  	<p class="text-right"><%= image_tag "jiefu-signature.png" %></p>
		  </div>
		</div>

		<div class="row about-contact">
	  	<div class="col-md-4">
	  		<blockquote class="blockquote-reverse certification-blockquote">
				  <h4 class="about-head"><%= t(".certification") %></h4>
				</blockquote>
	  	</div>
		  <div class="col-md-8">
		  	<p><%= link_to t(".honors"), about_honors_path %></p>
		  </div>
		</div>

		<div class="row about-contact">
	  	<div class="col-md-4">
	  		<blockquote class="blockquote-reverse certification-blockquote">
				  <h4 class="about-head"><%= t(".talent") %></h4>
				</blockquote>
	  	</div>
		  <div class="col-md-8">
		  	<p>
		  		<%= t(".talent_content") %>
		  	</p>
		  	<%= link_to t(".job"), careers_path, class: "btn btn-primary", type: "button" %>
		  </div>
		</div>

	</div>
</div>

app/views/static_pages/about_introduction.html.erb
<div class="introduction-jumbotron">
  <div class="container">
    <div class="content">
      <h2><%= t(".title") %></h2>
      <p><%= t(".title_content") %></p>
    </div>
  </div>
</div>

<div class="container introduction">
    <ol class="breadcrumb introduction_breadcrumb">
      <li><%= link_to (fa_icon "home"), root_path %></a></li>
      <li><%= link_to t(".about"), about_path %></li>
      <li class="active"><%= t(".profile") %></li>
    </ol>
	<div class="row contact">
	  <div class="col-md-12">
	  	<div class="introduction-text">
	  		<%= simple_format(@about.introduce) %>
	  	</div>
      <hr>
      <div class="embed-responsive embed-responsive-16by9">
        <video controls>
            <source src="http://op61r3aq7.bkt.clouddn.com/jiefu-web.mp4" type="video/mp4">
        </video>
      </div>
	  </div>
	</div>
</div>

app/views/static_pages/careers.html.erb
<div class="about-jumbotron">
  <div class="container">
    <div class="content">

    </div>
  </div>
</div>

<div class="container careers">

	<div class="row contact">
  	<div class="col-md-3">
			<section class="title-banner">
        <div class="banner-content">
          <h2 class="banner-title">你的明天，<br>杰夫的未来。</h2>
        </div>
    	</section>
			<p class="careers-small-title"><small>员工是我们宝贵的资产，我们以富有竞争力的管理方式和绩效考核对员工进行奖励，并给予员工明确的晋升计划。</small></p>

  	</div>

		<div class="col-md-7 col-md-offset-2">
			<table class="table table-hover careers-table">
				<thead>
					<tr>
						<th>职位</th>
						<th>区域</th>
						<th>人数</th>
					</tr>
				</thead>
	  		<tbody>
	  			<tr>
	  				<td><%= link_to "外贸业务人员", careers_detail_path, class: "carrers-link" %></td>
	  				<td>无锡</td>
	  				<td>2名</td>
	  			</tr>
	  			<tr>
	  				<td>IT管理员</td>
	  				<td>无锡</td>
	  				<td>1名</td>
	  			</tr>
	  			<tr>
	  				<td>技术开发助理</td>
	  				<td>无锡</td>
	  				<td>1名</td>
	  			</tr>
	  		</tbody>
	  	</table>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron banner">
  <div class="container">
    <div class="content">
      <h1><%= @home.copywrite1 if @home.copywrite1? %></h1>
			<h2><%= @home.copywrite2 if @home.copywrite2? %></h2>
    </div>
  </div>
</div>

<div class="jumbotron choose-product">
  <div class="container">
    <div class="content">
      <div class="row">
        <div class="col-xs-6"><h3><%= t(".new_speaker") %></h3></div>
        <div class="col-xs-6">
          <div class="dropdown choose">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%= t(".latest_products") %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to @home.newproduct1, product_path(prodcut_find(@home.newproduct1)) if @home.newproduct1?%></li>
              <li><%= link_to @home.newproduct2, product_path(prodcut_find(@home.newproduct2)) if @home.newproduct2?%></li>
              <li><%= link_to @home.newproduct3, product_path(prodcut_find(@home.newproduct3)) if @home.newproduct3?%></li>
              <li><%= link_to @home.newproduct4, product_path(prodcut_find(@home.newproduct4)) if @home.newproduct4?%></li>
              <li><%= link_to @home.newproduct5, product_path(prodcut_find(@home.newproduct5)) if @home.newproduct5?%></li>
              <li><%= link_to @home.newproduct6, product_path(prodcut_find(@home.newproduct6)) if @home.newproduct6?%></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="home-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="row home-product">
          <div class="col-md-6">
            <%= image_tag(prodcut_find(@home.mainproduct1).photo1.url, width: '200', class: "product-img") if @home.mainproduct1? %>
          </div>
          <div class="col-md-6">
            <h4><%= @home.mainproduct1 if @home.mainproduct1? %></h4>
            <p><%= truncate(prodcut_find(@home.mainproduct1).feature, escape: false, length: 70) if @home.mainproduct1? %></p>
            <%= link_to t(".view_details"), product_path(prodcut_find(@home.mainproduct1)), class: "btn btn-primary", role: "button" if @home.mainproduct1? %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="row home-product">
          <div class="col-md-6">
            <%= image_tag(prodcut_find(@home.mainproduct2).photo1.url, width: '200', class: "product-img") if @home.mainproduct2? %>
          </div>
          <div class="col-md-6">
            <h4><%= @home.mainproduct2 if @home.mainproduct2? %></h4>
            <p><%= truncate(prodcut_find(@home.mainproduct2).feature, escape: false, length: 70) if @home.mainproduct2? %></p>
            <%= link_to t(".view_details"), product_path(prodcut_find(@home.mainproduct2)), class: "btn btn-primary", role: "button" if @home.mainproduct2? %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="row home-product">
          <div class="col-md-6">
            <%= image_tag(prodcut_find(@home.mainproduct3).photo1.url, width: '200', class: "product-img") if @home.mainproduct3? %>
          </div>
          <div class="col-md-6">
            <h4><%= @home.mainproduct3 if @home.mainproduct3? %></h4>
            <p><%= truncate(prodcut_find(@home.mainproduct3).feature, escape: false, length: 70) if @home.mainproduct3? %></p>
            <%= link_to t(".view_details"), product_path(prodcut_find(@home.mainproduct3)), class: "btn btn-primary", role: "button" if @home.mainproduct3? %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="row home-product">
          <div class="col-md-6">
            <%= image_tag(prodcut_find(@home.mainproduct4).photo1.url, width: '200', class: "product-img") if @home.mainproduct4? %>
          </div>
          <div class="col-md-6">
            <h4><%= @home.mainproduct4 if @home.mainproduct4? %></h4>
            <p><%= truncate(prodcut_find(@home.mainproduct4).feature, escape: false, length: 70) if @home.mainproduct4? %></p>
            <%= link_to t(".view_details"), product_path(prodcut_find(@home.mainproduct4)), class: "btn btn-primary", role: "button" if @home.mainproduct4? %>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="home-content">
  <div class="container">
    <div class="row">
      <div class="col-md-6">

        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <%= image_tag("home-d.png") %>
            </div>
            <div class="item">
              <%= image_tag("home-aa.png") %>
            </div>
            <div class="item">
              <%= image_tag("home-u.png") %>
            </div>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
      <div class="col-md-6">
        <h1><%= t(".slogan") %></h1>
        <p><%= simple_format(@home.advantage) %></p>
      </div>
    </div>
  </div>
</div>

  <div class="container">
    <div class="row columns">
      <div class="col-md-3">
        <div class="home-box pic">
          <%= image_tag("home-box-b.png") %>
          <h5><%= t(".company_profile") %></h5>
          <h3><%= t(".company_profile_title") %></h3>
          <p><%= link_to t(".more"), about_introduction_path %></p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="home-box">
          <%= image_tag("home-box-c.png") %>
          <h5><%= t(".news") %></h5>
          <h3><%= t(".news_title1") %> <br> <%= t(".news_title2") %></h3>
          <p><%= link_to t(".more"), infos_path %></p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="home-box">
          <%= image_tag("home-box-a.png") %>
          <h5><%= t(".honors") %></h5>
          <h3><%= t(".honors_title") %></h3>
          <p><%= link_to t(".more"), about_honors_path %></p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="home-box">
          <%= image_tag("home-box-d.png") %>
          <h5><%= t(".job") %></h5>
          <h3><%= t(".job_title") %></h3>
          <p><%= link_to t(".more"), careers_path %></p>
        </div>
      </div>
    </div>
  </div> <!-- /container -->
</div>

app/views/static_pages/product.html.erb
<div class="product-banner">
	<div class="container">
    <div class="content">
      <h2>电视扬声器</h2>
      <p>高效节能的JIEFU电视扬声器可减少功耗，减轻重量并提供同样出色的动态表现与声学性能</p>
    </div>
  </div>
</div>

<div class="container product-list">
	<div class="row">
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><%= link_to '了解详细', product_detail_path %></p>
	  </div>
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><a href="#">了解详细</a></p>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><a href="#">了解详细</a></p>
	  </div>
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><a href="#">了解详细</a></p>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><a href="#">了解详细</a></p>
	  </div>
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><a href="#">了解详细</a></p>
	  </div>
	</div>
	<div class="row">
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><a href="#">了解详细</a></p>
	  </div>
	  <div class="col-md-6">
	  	<%= image_tag('product3.png', class: "product-img") %>
	  	<h4>YDP1580-2G</h4>
			<ul class="list-unstyled">
			  <li>外观尺寸（长*宽*高）mm : 80.0*14.5*13.0</li>
			  <li>阻抗（Ω）: 4/6/8/16</li>
			  <li>FO（Hz）: 280</li>
			  <li>额定功率（W）: 10</li>
			  <li>灵敏度（dB）: 80</li>
			  <li>频响范围 : Fo~20KHz</li>
			</ul>
			<p><a href="#">了解详细</a></p>
	  </div>
	</div>
	<nav>
	  <ul class="pagination">
	    <li>
	      <a href="#" aria-label="Previous">
	        <span aria-hidden="true">&laquo;</span>
	      </a>
	    </li>
	    <li><a href="#">1</a></li>
	    <li><a href="#">2</a></li>
	    <li><a href="#">3</a></li>
	    <li><a href="#">4</a></li>
	    <li><a href="#">5</a></li>
	    <li>
	      <a href="#" aria-label="Next">
	        <span aria-hidden="true">&raquo;</span>
	      </a>
	    </li>
	  </ul>
	</nav>
</div>

app/views/static_pages/terms_of_use.html.erb
<div class="container privacy">
	<h1><%= t(".title") %></h1>
	<hr>
	<h3><%= t(".disclaimer") %></h3>
	<p><%= t(".disclaimer_content") %></p>

	<h3><%= t(".international") %></h3>
	<p><%= t(".international_content") %></p>
</div>