config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    resources :products, only: [:index, :show]
    resources :infos, only:[:index, :show]
    resources :careers, only: [:index, :show]

    resource :search, only: :show
    resources :messages, only: [:new, :create]

    get 'product' => 'static_pages#product'
    get 'product_detail' => 'static_pages#product_detail'
    get 'laboratory' => 'static_pages#laboratory'
    get 'support' => 'static_pages#support'
    get 'privacy' => 'static_pages#privacy'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'static_search' => 'static_pages#search'

    get 'about' => 'static_pages#about'
    get 'about_introduction' => 'static_pages#about_introduction'
    get 'about_honors' => 'static_pages#about_honors'

    # get 'careers' => 'static_pages#careers'
    get 'careers_detail' => 'static_pages#careers_detail'

    namespace :admin do
      root 'home#show', as: 'root'
      resources :home, only: [:show, :edit, :update]
      resources :products
      resources :infos do
        collection do
          post :upload
        end
      end
      resources :about, only: [:show, :edit, :update]
      resources :laboratories, only: [:show, :edit, :update]
      resources :careers
      resources :users, except: [:show, :edit, :update]
      resources :messages, except: [:new, :create]

      get '/login', to: 'sessions#new'
      post '/login', to:'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :photo1, presence: true
	validates :photo2, presence: true

	translates :feature

	mount_uploader :photo1, PhotoUploader
	mount_uploader :photo2, PhotoUploader
	mount_uploader :configuration1, PhotoUploader
	mount_uploader :configuration2, PhotoUploader
	mount_uploader :curve1, PhotoUploader
	mount_uploader :curve2, PhotoUploader



	# def self.search(search)
	#   if search
	#     where("name = ?", "#{search}")
	#   else
	#     all
	#   end
	# end


end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    before_action :logged_in_user
    
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    # GET /admin/products
    # GET /admin/products.json
    def index
      @products = Product.all
    end

    # GET /admin/products/1
    # GET /admin/products/1.json
    def show
    end

    # GET /admin/products/new
    def new
      @product = Product.new
    end

    # GET /admin/products/1/edit
    def edit

    end

    # POST /admin/products
    # POST /admin/products.json
    def create
      @product = Product.new(params[:product].permit!)

      respond_to do |format|
        if @product.save
          flash[:success] = "创建成功!"
          format.html { redirect_to admin_products_url }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /admin/products/1
    # PATCH/PUT /admin/products/1.json
    def update
      respond_to do |format|
        if @product.update(params[:product].permit!)
          flash[:success] = "更新成功!"
          format.html { redirect_to admin_products_url }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /admin/products/1
    # DELETE /admin/products/1.json
    def destroy
      @product.destroy
      flash[:success] = "删除成功!"
      respond_to do |format|
        format.html { redirect_to admin_products_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  	# @products = Product.search(params[:search])
  	# @products = Product.where(category: params[:category])
  	@products = Product.paginate(page: params[:page], :per_page => 12)
  end

  def show
  	@product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h3>修改扬声器</h3>
<br>

<%= form_for @product, url: admin_product_path(@product) do |f| %>
  <%= render 'admin/shared/error_messages', object: @product %>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <td colspan="2"><%= f.label :name, "扬声器型号" %></td>
        <td class="table-left"><%= f.text_field :name, class: 'form-control' %></td>
      </tr>
      <tr>
        <td colspan="2"><%= f.label :product_type, "扬声器类型" %></td>
        <td><%= f.select(:product_type, options_for_select([['单体扬声器', 1], ['箱体扬声器', 2], ['汽车扬声器', 3]],f.object.product_type), class: "form-control") %></td>
      </tr>
<!--       <tr>
        <td colspan="2"><%#= f.label :category, "扬声器分类" %></td>
        <td><%#= f.select(:category, options_for_select([['电视扬声器', 1], ['其他扬声器', 2]], f.object.category), class: "form-control") %></td>
      </tr> -->
      <tr>
        <td rowspan="6">参数</td>
        <td>外观尺寸（长*宽*高）:</td>
        <td>*<%= f.label :size_length, "长" %> <%= f.text_field :size_length, class: 'form-control parameter_size' %>*<%= f.label :size_width, "宽" %><%= f.text_field :size_width, class: 'form-control parameter_size' %>*<%= f.label :size_height, "高" %><%= f.text_field :size_height, class: 'form-control parameter_size' %></td>
      </tr>
          <tr>
            <td><%= f.label :impedance, "阻抗（Ω）" %></td>
            <td><%= f.text_field :impedance, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :fo, "FO（Hz）" %></td>
            <td><%= f.text_field :fo, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :rated_power, "额定功率（W）" %></td>
            <td><%= f.text_field :rated_power, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :sensitivity, "灵敏度（dB）" %></td>
            <td><%= f.text_field :sensitivity, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :frequency, "频响范围" %></td>
            <td><%= f.text_field :frequency, class: 'form-control' %></td>
          </tr>
      <tr>
        <td colspan="2"><%= f.label :feature, "特点" %></td>
        <td><%= f.text_area :feature, placeholder: "...", class: 'form-control' %></td>
      </tr>
      <tr>
        <td colspan="2">扬声器图-1</td>
        <td><%= image_tag(@product.photo1_url, width: '260', class: "product-img") if @product.photo1? %><%= f.file_field :photo1 %></td>
      </tr>
      <tr>
        <td colspan="2">扬声器图-2</td>
        <td><%= image_tag(@product.photo2.url, width: '260', class: "product-img") if @product.photo2? %><%= f.file_field :photo2 %></td>
      </tr>
      <tr>
        <td colspan="2">外形结构图-1</td>
        <td><%= image_tag(@product.configuration1.url, width: '260', class: "product-img") if @product.configuration1? %><%= f.file_field :configuration1 %></td>
      </tr>
      <tr>
        <td colspan="2">外形结构图-2</td>
        <td><%= image_tag(@product.configuration2.url, width: '260', class: "product-img") if @product.configuration2? %><%= f.file_field :configuration2 %></td>
      </tr>
      <tr>
        <td colspan="2">曲线图-1</td>
        <td><%= image_tag(@product.curve1.url, width: '260', class: "product-img") if @product.curve1? %><%= f.file_field :curve1 %></td>
      </tr>
      <tr>
        <td colspan="2">曲线图-2</td>
        <td><%= image_tag(@product.curve2.url, width: '260', class: "product-img") if @product.curve2? %><%= f.file_field :curve2 %></td>
      </tr>
    </tbody>
  </table>

  <%= f.submit "修改产品", class: "btn btn-primary" %>

<% end %>

<%= link_to '返回', admin_products_path %>

app/views/admin/products/index.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<h3>产品列表</h3>
<br>
<%= link_to '新建扬声器', new_admin_product_path, class: "btn btn-primary" %>

<table class="table table-hover">
  <thead>
    <tr>
<!--       <th class="table-list-a"><h4>扬声器分类</h4></th> -->
      <th class="table-list-a"><h4>类型</h4></th>
      <th><h4>型号</h4></th>
      <th><h4>图片</h4></th>
      <th colspan="2"><h4>编辑</h4></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
<!--         <td><%#= full_category(product.category) %></td> -->
        <td><%= full_product_type(product.product_type) %></td>
        <td><%= link_to product.name, admin_product_path(product) %></td>
        <td><%= image_tag(product.photo1.url, width: '80', class: "product-img") if product.photo1? %></td>
        <td><%= link_to '修改', edit_admin_product_path(product) %></td>
        <td><%= link_to '删除', admin_product_path(product), method: :delete, data: { confirm: '确定删除?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h3>创建扬声器</h3>
<br>

<%= form_for(@product, url: admin_products_path, html: { multipart: true }) do |f| %>
  <%= render 'admin/shared/error_messages', object: @product %>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <td colspan="2"><%= f.label :name, "扬声器型号" %></td>
        <td class="table-left"><%= f.text_field :name, class: 'form-control' %></td>
      </tr>
      <tr>
        <td colspan="2"><%= f.label :product_type, "扬声器类型" %></td>
        <td><%= f.select(:product_type, options_for_select([['单体扬声器', 1], ['箱体扬声器', 2], ['汽车扬声器', 3]]), class: "form-control") %></td>
      </tr>
<!--       <tr>
        <td colspan="2"><%#= f.label :category, "扬声器分类" %></td>
        <td><%#= f.select(:category, options_for_select([['电视扬声器', 1], ['其他扬声器', 2]]), class: "form-control") %></td>
      </tr> -->
      <tr>
        <td rowspan="6">参数</td>
        <td>外观尺寸（长*宽*高）:</td>
        <td>*<%= f.label :size_length, "长" %> <%= f.text_field :size_length, class: 'form-control parameter_size' %>*<%= f.label :size_width, "宽" %><%= f.text_field :size_width, class: 'form-control parameter_size' %>*<%= f.label :size_height, "高" %><%= f.text_field :size_height, class: 'form-control parameter_size' %></td>
      </tr>
          <tr>
            <td><%= f.label :impedance, "阻抗（Ω）" %></td>
            <td><%= f.text_field :impedance, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :fo, "FO（Hz）" %></td>
            <td><%= f.text_field :fo, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :rated_power, "额定功率（W）" %></td>
            <td><%= f.text_field :rated_power, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :sensitivity, "灵敏度（dB）" %></td>
            <td><%= f.text_field :sensitivity, class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label :frequency, "频响范围" %></td>
            <td><%= f.text_field :frequency, class: 'form-control' %></td>
          </tr>
      <tr>
        <td colspan="2"><%= f.label :feature, "特点" %></td>
        <td><%= f.text_area :feature, placeholder: "...", class: 'form-control' %></td>
      </tr>
      <tr>
        <td colspan="2">扬声器图-1</td>
        <td><%= f.file_field :photo1 %></td>
      </tr>
      <tr>
        <td colspan="2">扬声器图-2</td>
        <td><%= f.file_field :photo2 %></td>
      </tr>
      <tr>
        <td colspan="2">外形结构图-1</td>
        <td><%= f.file_field :configuration1 %></td>
      </tr>
      <tr>
        <td colspan="2">外形结构图-2</td>
        <td><%= f.file_field :configuration2 %></td>
      </tr>
      <tr>
        <td colspan="2">曲线图-1</td>
        <td><%= f.file_field :curve1 %></td>
      </tr>
      <tr>
        <td colspan="2">曲线图-2</td>
        <td><%= f.file_field :curve2 %></td>
      </tr>
    </tbody>
  </table>

  <%= f.submit "创建产品", class: "btn btn-primary" %>

<% end %>

<br>
<%= link_to '返回', admin_products_path %>

app/views/admin/products/show.html.erb
<p><%= link_to '返回', admin_products_path %> |
 <%= link_to '修改', edit_admin_product_path(@product) %>
</p>

<table class="table table-bordered">
  <tbody>
    <tr>
      <td colspan="2">扬声器型号</td>
      <td  class="table-left"><%= @product.name %></td>
    </tr>
    <tr>
        <td colspan="2">扬声器类型</td>
        <td><%= full_product_type(@product.product_type) %></td>
    </tr>
<!--     <tr>
    	<td colspan="2">扬声器分类</td>
    	<td><%#= full_category(@product.category) %></td>
    </tr> -->
    <tr>
    	<td rowspan="6">参数</td>
    	<td>外观尺寸（长*宽*高）:</td>
    	<td>mm : <%= @product.size_length %>*<%= @product.size_width %>*<%= @product.size_height %></td>
    </tr>
		    <tr>
		    	<td>阻抗（Ω）:</td>
		    	<td><%= @product.impedance %></td>
		    </tr>
		    <tr>
		    	<td>FO（Hz）:</td>
		    	<td><%= @product.fo %></td>
		    </tr>
		    <tr>
		    	<td>额定功率（W）:</td>
		    	<td><%= @product.rated_power %></td>
		    </tr>
		    <tr>
		    	<td>灵敏度（dB）:</td>
		    	<td><%= @product.sensitivity %></td>
		    </tr>
		    <tr>
		    	<td>频响范围:</td>
		    	<td><%= @product.frequency %></td>
		    </tr>
		<tr>
    	<td colspan="2">特点</td>
    	<td><%= @product.feature %></td>
    </tr>
    <tr>
        <td colspan="2">扬声器图-1</td>
        <td><%= image_tag(@product.photo1.url, width: '260', class: "product-img") if @product.photo1? %></td>
    </tr>
    <tr>
        <td colspan="2">扬声器图-2</td>
        <td><%= image_tag(@product.photo2.url, width: '260', class: "product-img") if @product.photo2? %></td>
    </tr>
    <tr>
    	<td colspan="2">外形结构图-1</td>
    	<td><%= image_tag(@product.configuration1.url, width: '260', class: "product-img") if @product.configuration1? %></td>
    </tr>
    <tr>
    	<td colspan="2">外形结构图-2</td>
    	<td><%= image_tag(@product.configuration2.url, width: '260', class: "product-img") if @product.configuration2? %></td>
    </tr>
    <tr>
    	<td colspan="2">曲线图-1</td>
    	<td><%= image_tag(@product.curve1.url, width: '260', class: "product-img") if @product.curve1? %></td>
    </tr>
    <tr>
    	<td colspan="2">曲线图-2</td>
    	<td><%= image_tag(@product.curve2.url, width: '260', class: "product-img") if @product.curve2? %></td>
    </tr>
  </tbody>
</table>