config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    resources :products, only: [:index, :show]
    resources :infos, only:[:index, :show]
    resources :careers, only: [:index, :show]

    resource :search, only: :show
    resources :messages, only: [:new, :create]

    get 'product' => 'static_pages#product'
    get 'product_detail' => 'static_pages#product_detail'
    get 'laboratory' => 'static_pages#laboratory'
    get 'support' => 'static_pages#support'
    get 'privacy' => 'static_pages#privacy'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'static_search' => 'static_pages#search'

    get 'about' => 'static_pages#about'
    get 'about_introduction' => 'static_pages#about_introduction'
    get 'about_honors' => 'static_pages#about_honors'

    # get 'careers' => 'static_pages#careers'
    get 'careers_detail' => 'static_pages#careers_detail'

    namespace :admin do
      root 'home#show', as: 'root'
      resources :home, only: [:show, :edit, :update]
      resources :products
      resources :infos do
        collection do
          post :upload
        end
      end
      resources :about, only: [:show, :edit, :update]
      resources :laboratories, only: [:show, :edit, :update]
      resources :careers
      resources :users, except: [:show, :edit, :update]
      resources :messages, except: [:new, :create]

      get '/login', to: 'sessions#new'
      post '/login', to:'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

	before_save { self.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
						format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :logged_in_user
    
    before_action :set_admin_user, only: :destroy

    # GET /admin/users
    # GET /admin/users.json
    def index
      @admin_users = User.all
    end


    # GET /admin/users/new
    def new
      @admin_user = User.new
    end


    # POST /admin/users
    # POST /admin/users.json
    def create
      @admin_user = User.new(params[:user].permit!)

      respond_to do |format|
        if @admin_user.save
          flash[:success] = "创建成功!"

          format.html { redirect_to admin_users_url }
        else
          format.html { render :new }
        end
      end
    end

    # DELETE /admin/users/1
    # DELETE /admin/users/1.json
    def destroy
      @admin_user.destroy
      flash[:success] = "删除成功!"
      respond_to do |format|
        format.html { redirect_to admin_users_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_user
        @admin_user = User.find(params[:id])
      end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(admin_user) do |f| %>
  <% if admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing Admin User</h1>

<%= render 'form', admin_user: @admin_user %>

<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<h3>管理员列表</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="table-list-a"><h4>管理员</h4></th>
      <th><h4>登录邮箱</h4></th>
      <th colspan="2"><h4>编辑</h4></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= link_to admin_user.name, admin_user_path(admin_user) %></td>
        <td><%= link_to admin_user.email, admin_user_path(admin_user) %></td>
        <td><%= link_to '删除', admin_user_path(admin_user), method: :delete, data: { confirm: '确认删除?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '添加管理员', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h3>添加管理员</h3>
<br>
<div class="row">
	<div class="col-md-6">
		<%= form_for(@admin_user, url: admin_users_path) do |f| %> 
			<%= render 'admin/shared/error_messages', object: @admin_user %>
			<div class="form-group">
				<%= f.label :name, "管理员名字" %>
				<%= f.text_field :name, class: 'form-control' %>
			</div>

			<div class="form-group">
		    <%= f.label :email, "登录邮箱" %>
		    <%= f.email_field :email, class: 'form-control' %>
	    </div>
			
			<div class="form-group">
		    <%= f.label :password, "设置密码" %>
		    <%= f.password_field :password, class: 'form-control' %>
			</div>

			<div class="form-group">
		    <%= f.label :password_confirmation, "重复密码" %>
		    <%= f.password_field :password_confirmation, class: 'form-control' %>
			</div>
			
			<br>
			<%= f.submit "创建管理员", class: "btn btn-primary" %> 
		<% end %>
	</div>
</div>


<%= link_to '返回', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>