config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'static_pages#home'

    resources :products, only: [:index, :show]
    resources :infos, only:[:index, :show]
    resources :careers, only: [:index, :show]

    resource :search, only: :show
    resources :messages, only: [:new, :create]

    get 'product' => 'static_pages#product'
    get 'product_detail' => 'static_pages#product_detail'
    get 'laboratory' => 'static_pages#laboratory'
    get 'support' => 'static_pages#support'
    get 'privacy' => 'static_pages#privacy'
    get 'terms_of_use' => 'static_pages#terms_of_use'
    get 'static_search' => 'static_pages#search'

    get 'about' => 'static_pages#about'
    get 'about_introduction' => 'static_pages#about_introduction'
    get 'about_honors' => 'static_pages#about_honors'

    # get 'careers' => 'static_pages#careers'
    get 'careers_detail' => 'static_pages#careers_detail'

    namespace :admin do
      root 'home#show', as: 'root'
      resources :home, only: [:show, :edit, :update]
      resources :products
      resources :infos do
        collection do
          post :upload
        end
      end
      resources :about, only: [:show, :edit, :update]
      resources :laboratories, only: [:show, :edit, :update]
      resources :careers
      resources :users, except: [:show, :edit, :update]
      resources :messages, except: [:new, :create]

      get '/login', to: 'sessions#new'
      post '/login', to:'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :photo1, presence: true
	validates :photo2, presence: true

	translates :feature

	mount_uploader :photo1, PhotoUploader
	mount_uploader :photo2, PhotoUploader
	mount_uploader :configuration1, PhotoUploader
	mount_uploader :configuration2, PhotoUploader
	mount_uploader :curve1, PhotoUploader
	mount_uploader :curve2, PhotoUploader



	# def self.search(search)
	#   if search
	#     where("name = ?", "#{search}")
	#   else
	#     all
	#   end
	# end


end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    before_action :logged_in_user
    
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    # GET /admin/products
    # GET /admin/products.json
    def index
      @products = Product.all
    end

    # GET /admin/products/1
    # GET /admin/products/1.json
    def show
    end

    # GET /admin/products/new
    def new
      @product = Product.new
    end

    # GET /admin/products/1/edit
    def edit

    end

    # POST /admin/products
    # POST /admin/products.json
    def create
      @product = Product.new(params[:product].permit!)

      respond_to do |format|
        if @product.save
          flash[:success] = "创建成功!"
          format.html { redirect_to admin_products_url }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /admin/products/1
    # PATCH/PUT /admin/products/1.json
    def update
      respond_to do |format|
        if @product.update(params[:product].permit!)
          flash[:success] = "更新成功!"
          format.html { redirect_to admin_products_url }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /admin/products/1
    # DELETE /admin/products/1.json
    def destroy
      @product.destroy
      flash[:success] = "删除成功!"
      respond_to do |format|
        format.html { redirect_to admin_products_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  	# @products = Product.search(params[:search])
  	# @products = Product.where(category: params[:category])
  	@products = Product.paginate(page: params[:page], :per_page => 12)
  end

  def show
  	@product = Product.find(params[:id])
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<% provide(:title, "扬声器") %>

<div class="product-banner">
	<div class="container">
    <div class="content">
      <h2><%= t(".title") %></h2>
      <p><%= t(".content") %></p>
    </div>
  </div>
</div>

<div class="container product-list">

	<div class="btn-group advanced-search">
		<%= link_to search_path, class: "btn btn-primary" do %>
	    <i class="glyphicon glyphicon-search"></i> <%= t(".search") %>
		<% end %>
	</div>

	<% @products.each_slice(2) do |products| %>
		<div class="row">
			<% products.each do |product| %>
				<div class="col-md-6">
					<%= image_tag(product.photo1.url, class: "product-img") if product.photo1? %>
			  	<h4><%= product.name %></h4>
					<ul class="list-unstyled">
					  <li><%= t("products.size") %>mm : <%= product.size_length %>*<%= product.size_width %>*<%= product.size_height %></li>
					  <li><%= t("products.impedance") %>（Ω）: <%= product.impedance %></li>
					  <li>FO（Hz）: <%= product.fo %></li>
					  <li><%= t("products.rated_power") %>（W）: <%= product.rated_power %></li>
					  <li><%= t("products.sensitivity") %>（dB）: <%= product.sensitivity %></li>
					  <li><%= t("products.frequency") %> : <%= product.frequency %></li>
					</ul>
					<p><%= link_to t(".view_details"), product_path(product) %></p>
			  </div>
			<% end %>
		</div>
	<% end %>

	<%= will_paginate %>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>
<div class="container news_list">
	<ol class="breadcrumb news_breadcrumb">
	  <li><%= link_to t(".return"), products_path %></li>
	</ol>

	<div class="container product_detail">
		<div class="row">
		  <div class="col-md-6 product_detail_img">
			  <div class="tab-content">
			    <div role="tabpanel" class="tab-pane active" id="photo-a">
			    	<%= image_tag(@product.photo1_url, class: "product-img") if @product.photo1? %>
			    </div>
			    <div role="tabpanel" class="tab-pane" id="photo-b">
			    	<%= image_tag(@product.photo2_url, class: "product-img") if @product.photo2? %>
			    </div>
			  </div>
			  <ul class="nav nav-pills product_detail_img_list" role="tablist">
			    <li role="presentation" class="active"><a href="#photo-a" aria-controls="photo-a" role="tab" data-toggle="tab"><%= image_tag(@product.photo1.url, width: '80', class: "img-thumbnail") if @product.photo1? %></a></li>
			    <li role="presentation"><a href="#photo-b" aria-controls="photo-b" role="tab" data-toggle="tab"><%= image_tag(@product.photo2.url, width: '80', class: "img-thumbnail") if @product.photo1? %></a></li>
			  </ul>
		  </div>
		  <div class="col-md-6 product_detail_text">
		  	<h2><%= @product.name %></h2>

				<div class="product_detail_content">
				  <!-- Nav tabs -->
				  <ul class="nav nav-pills" role="tablist">
				  	<li role="presentation" class="active"><a href="#parameter" aria-controls="parameter" role="tab" data-toggle="tab"><%= t(".parameter") %></a></li>
				    <li role="presentation"><a href="#feature" aria-controls="feature" role="tab" data-toggle="tab"><%= t(".feature") %></a></li>
				    <li role="presentation"><a href="#construction" aria-controls="construction" role="tab" data-toggle="tab"><%= t(".construction") %></a></li>
				    <li role="presentation"><a href="#graph" aria-controls="graph" role="tab" data-toggle="tab"><%= t(".graph") %></a></li>
				  </ul>

				  <!-- Tab panes -->
				  <div class="tab-content">
				  	<div role="tabpanel" class="tab-pane active" id="parameter">
				    	<ul class="list-unstyled">
							  <li><%= t("products.size") %>mm : <%= @product.size_length %>*<%= @product.size_width %>*<%= @product.size_height %></li>
							  <li><%= t("products.impedance") %>（Ω）: <%= @product.impedance %></li>
							  <li>FO（Hz）: <%= @product.fo %></li>
							  <li><%= t("products.rated_power") %>: <%= @product.rated_power %></li>
							  <li><%= t("products.sensitivity") %>（dB）: <%= @product.sensitivity %></li>
							  <li><%= t("products.frequency") %> : <%= @product.frequency %></li>
							</ul>
				    </div>
				    <div role="tabpanel" class="tab-pane" id="feature">
				    	<p><%= @product.feature %></p>
				    </div>
				    <div role="tabpanel" class="tab-pane" id="construction">
				    	<%= image_tag(@product.configuration1.url, class: "product-img") if @product.configuration1? %>
				    	<%= image_tag(@product.configuration1.url, class: "product-img") if @product.configuration1? %>
				    </div>
				    <div role="tabpanel" class="tab-pane" id="graph">
				    	<%= image_tag(@product.curve1.url, class: "product-img") if @product.curve1? %>
				    	<%= image_tag(@product.curve2.url, class: "product-img") if @product.curve2? %>
				    </div>
				  </div>
				</div>
				
				<%= link_to t(".support"), support_path, html_options = { class: "btn btn-primary", role: "button"} %>
		  </div>
		</div>
	</div>
</div>